config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  resources :posts do
    collection do
      get "/posts?page_size=[:page_size]&offset=[:page]" => "posts#index"
      get :search
    end
  end

  resources :tags, only: [:show] do
    resources :posts, only: [:index, :create]
    scope "/questions" do
      resources :posts, only: [:index, :create]
    end
  end

end

app/models/geek.rb
class Geek < ActiveRecord::Base
  has_many :posts, foreign_key: :owner_user_id
  has_many :questions, class_name: "Post", foreign_key: :owner_user_id
  has_many :answers, class_name: "Post", foreign_key: :owner_user_id

end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :post_tags, dependent: :destroy
  has_many :tags, through: :post_tags
  has_many :answers, class_name: "Post", foreign_key: :parent_id
  belongs_to :question, class_name: "Post", foreign_key: :parent_id
  belongs_to :author, class_name: "Geek", foreign_key: :owner_user_id

  scope :questions, proc { where(parent_id: nil) } 
  scope :paginated, ->(page_number, page_size) { limit(page_size).offset((page_number - 1) * page_size) }

  after_create :send_notification_email


  def self.search_results(search_term, page_number, page_size)
    self.search("*" + search_term + "*", ranker: :bm25,
	       	per_page: page_size, page: page_number, sql: { include: :tags })
  end

  def self.no_next(next_page_number, page_size)
    self.paginated(next_page_number, page_size).empty?
  end

  def self.no_next_search(next_search_term, page_number, page_size)
    self.search_results(next_search_term, page_number, page_size).empty?
  end


  private
    def is_answer?
      parent_id
    end

    def send_notification_email
      PostMailer.notify_answer(self).deliver_now if is_answer?
    end
end

app/models/post_tag.rb
class PostTag < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :post_tags, dependent: :destroy
  has_many :posts, through: :post_tags

  scope :tagged_with, ->(name) { where(name: name) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
#  include ApplicationHelper
end

app/controllers/posts_controller.rb
require "./lib/search.rb"
class PostsController < ApplicationController
  before_action :paginate_variables, except: [:show, :create]

  def index
    @posts = Post.includes(:tags).paginated(@page_number, @page_size)
    @tags = Tag.all
  end

  def search
    @search_term = params[:search_term]
    @posts = Post.search_results(@search_term, @page_number, @page_size)
    @total_results = @posts.meta["total"].to_i
    @suggestion = Search.make_suggestion(@search_term, @total_results)
  end

  def show
    @post = Post.includes(:tags).find(params[:id])
  end

  def create
    #@answer = Post.create(post_params, author: current_geek)
    @answer = Post.new(post_params)
    @answer.author = current_geek
    @answer.save!
    if @answer.save
      redirect_to post_path(id: @answer.parent_id), notice: t("posts.created")
    else
      render :show
    end
  end


  private

    def paginate_variables
      @page_number = params[:page].nil? ? 1 : params[:page].to_i
      @page_size = params[:page_size].nil? ? 20 : params[:page_size].to_i
      @next_page = @page_number + 1
      @previous_page = @page_number - 1
    end

    def post_params
      params.require(:post).permit(:parent_id, :title, :body)
    end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def show
    @tag = Tag.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  Speller = FFI::Aspell::Speller.new('en_US')

  def did_you_mean(typo)
    suggestions = Speller.suggestions(typo)
    suggestions.map!{ |term| [Post.search(term).meta["total"].to_i, term] }.max
  end

  def spell_check?(term, total_results)
    total_results.zero? || (!Speller.correct?(term) && total_results.zero?)
  end

  def make_suggestion(search_term, total_results)
    if spell_check?(search_term, total_results)
      did_you_mean(search_term)[1]
    end
  end

end

app/views/layouts/_alerts.html.haml
.flash
  .notice
    = notice
  .alert
    = alert

app/views/layouts/_search_box.html.haml
.search-box
  = form_tag search_posts_path, method: :get do
    %fieldset
      = text_field_tag "search_term", nil, placeholder: "Please enter a search term..."
      = submit_tag "Search"

app/views/layouts/application.html.haml
!!! 5
%html{lang: 'en'}
  %head
    %title Information Mine
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = render "layouts/alerts"

    %nav
      %h1 Information Mine
      = yield :nav
      = render "layouts/search_box"
    
    %main#content
      = yield

    %footer

app/views/posts/_answer.html.haml
%li
  %article.post
    %header
      %h3= answer.title

    %p= answer.body.html_safe unless answer.body.nil?

    %footer
      %dl.inline
        %dt Created At
        %dd= answer.created_at
        %dt Tags
        %dd= answer.tags.map(&:name)

app/views/posts/_post.html.haml
%li
  %article.post
    %header
      %h3= post.title

    = link_to "Read more", post_path(post)

    %footer
      %dl.inline
        %dt Created At
        %dd= post.created_at
        %dt Tags
        %dd= post.tags.map(&:name).split(" ")

app/views/posts/index.html.haml
%ul
  = render @posts
%ul#tag-cloud
  - @tags.each do |tag|
    %li= link_to tag.name, tag_path(tag)

- unless @previous_page.zero?
  = link_to "Previous", posts_path(page_size: @page_size, page: @previous_page)
- unless Post.includes(:tags).no_next(@next_page, @page_size)
  = link_to "Next", posts_path(page_size: @page_size, page: @next_page)

app/views/posts/search.html.haml
%h2 
  Search Results for 
  = @search_term

.result-count
  Found 
  %span.result-count= @total_results
  results.

- unless @suggestion.nil?
  Did you mean #{link_to @suggestion, search_posts_path(search_term: @suggestion)}?

.search-results
  %ul
    = render @posts

- unless @previous_page.zero?
  = link_to "Previous", search_posts_path(search_term: @search_term,
					    per_page: @page_size, page: @previous_page)

- unless Post.no_next_search(@search_term, @next_page, @page_size)
  = link_to "Next", search_posts_path(search_term: @search_term, 
					per_page: @page_size, page: @next_page)

app/views/posts/show.html.haml
%article.post
  %header
    %h3= @post.title

  %p= @post.body.html_safe

  %footer
    %dl.inline
      %dt Created At
      %dd= @post.created_at
      %dt Tags
      %dd= @post.tags.map(&:name)

.new-form
  =form_for @post.answers.build do |f|
    = f.hidden_field :parent_id, value: @post.id
    %fieldset
      = f.label :title
      = f.text_field :title, value: @post.title
    %fieldset
      = f.label :body
      = f.text_area :body
    %fieldset
      = f.submit "Submit Answer"

%ol.answers
  - @post.answers.each do |answer|
    = render partial: "posts/answer", locals: { answer: answer }

app/views/tags/show.html.haml
%h1= @tag.name
%ol.posts
  - @tag.posts.each do |post|
    = render partial: "posts/post", locals: { post: post }